# Generated by Django 4.2.2 on 2023-06-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='original_language',
        ),
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('ENG', 'English'), ('POL', 'Polish'), ('ENG-SUB', 'English with polish subtitles'), ('POL-DUB', 'Polish dubbing')], default='ENG', max_length=30),
        ),
    ]
