# Generated by Django 4.2.2 on 2023-06-11 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_movie_original_language_movie_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='room',
        ),
    ]
