# Generated by Django 4.2.2 on 2023-06-11 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_seat_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='movie',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.movie'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='seat',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.seat'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.userprofile'),
        ),
    ]
