# Generated by Django 4.2.2 on 2023-06-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_ticket_movie_ticket_seat_ticket_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_price',
            field=models.FloatField(default=20.0),
        ),
    ]
