# Generated by Django 4.2.2 on 2023-06-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_room_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=4),
        ),
    ]
