# Generated by Django 4.2.2 on 2023-06-19 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_movie_ticket_price_alter_ticket_ticket_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=7),
        ),
    ]
