# Generated by Django 4.2.2 on 2023-06-19 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_movie_ticket_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='ticket_price',
            field=models.IntegerField(default=20),
        ),
    ]
