# Generated by Django 4.2.2 on 2023-06-19 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_movie_popularity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='popularity',
            field=models.DecimalField(decimal_places=7, max_digits=7, null=True),
        ),
    ]
