# Generated by Django 4.2.2 on 2023-06-19 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_movie_popularity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='popularity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='ticket_price',
            field=models.FloatField(default=20.0),
        ),
    ]
